version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/stevenmatthewt/template
    steps:
      - checkout
      - run:
          name: Unit tests
          command: |
            go test -v ./...
      - run: 
          name: Fmt
          command: go fmt ./...
      - run: 
          name: Vet
          command: go vet ./... 
      - run:
          name: Functional test
          command: |
            go run cmd/cli/main.go    \
            --template=./test_project \
            --destination=test_output \
            <<EOF
            yes
            No
            Y
            projectTest
            var1
            var2
            EOF

workflows:
  version: 2
  build->deploy:
    jobs:
      - build