version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/stevenmatthewt/template
    steps:
      - checkout
      - run: 
          name: Build
          command: go build -v ./cmd/cli
      - run: 
          name: Fmt
          command: go fmt ./...
      - run: 
          name: Vet
          command: go vet ./... 
      - run:
          name: Unit tests
          command: |
            go test -v $(go list ./... | grep -v /vendor) 

workflows:
  version: 2
  build->deploy:
    jobs:
      - build